[package]
name = "anthropic-stream"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anthropic-rs = { path = "../../anthropic" }
futures-util = "0.3.30"
tokio = { version = "1.39.2", features = ["full"] }
